##########################################################################
#            Multiverse Teleport Filter Configuration                    #
#                                                                        #
# See http://sleepydragn1.github.io/multiverse-teleportfilter/config for #
#         information about formatting and example configs.              #
#                                                                        #
##########################################################################

options:
    enabled: false
    soft-disable: false
    ignore-permissions: false
    ignore-core-version-check: false
teleportfilter:
    exampledestinationworld1:
        - exampleoriginworld1
        - exampleoriginworld2
    exampledestinationworld2:
        - all