##########################################################################
#            Multiverse Teleport Filter Configuration                    #
#                                                                        #
#     Information about formatting and example configs coming soon.      #
#                                                                        #
##########################################################################

options:
    enabled: true
    soft-disable: false
    ignore-filter-permissions: false
    ignore-core-version-check: false
teleportfilter:
    exampledestinationworld1:
        - exampleoriginworld1
        - exampleoriginworld2
    exampledestinationworld2:
        - all