##################################################################################
#                 Multiverse Teleport Filter Configuration                       #
#                                                                                #
#           You can find configuration information and examples at               #
#  https://github.com/Sleepydragn1/Multiverse-TeleportFilter/wiki/Configuration  #
#                                                                                #
##################################################################################

options:
    enabled: false
    filter-disabled: false
    ignore-filter-permissions: false
    ye-olde-op-system: false
    ignore-core-version-check: false
teleportfilter:
    exampledestinationworld1:
        - exampleoriginworld1
        - exampleoriginworld2
    exampledestinationworld2:
        - all