name: Multiverse-TeleportFilter
main: io.github.sleepydragn1.MultiverseTeleportFilter.MultiverseTeleportFilter
authors: ['Sleepydragn1']
version: 1.0
depend: ['Multiverse-Core']
permissions:
    multiverse.teleportfilter.bypass:
        description: Allows players to bypass the teleport filter and teleport to any world they have access to.
        default: op